### ISSUE TITLE
0.4 tracker [OLD]

### ISSUE THREAD

**Issue by Relintai** [Relintai/broken_seals#3]
This issue tries to track what I think needs to be done to (hopefully) make the game actually a game.

---
Classes

- [ ] Fix/implement all of Naturalist's spells
- [ ] Add more talents for Naturalist
- [ ] Add more classes (at least 2 for now)

---
Models / animations

- [ ] Add a human male model
- [ ] Make the human female model look less bad
- [ ] (Maybe) add more races
- [ ] Add / create animal models
- [ ] Create melee animations
- [ ] Implement melee attack animations (godot side) - Needs animation blending/layers too
- [ ] Add variations for the human
- [ ] Finish up EntitySpeciesInstance
- [ ] Jump animations, and implement jumping

---
Outdoor props

- [ ] Add a few basic props like trees, bushes, (maybe) flowers, fences etc.
- [ ] Create a few buildings. Maybe these could be procedurally generated using the prop system.
- [ ] This system could also do smaller outdoor "dungeons" like forts for example.

---
Level generation

- [ ] Implement continent generation.
- [ ] Villages.
- [ ] More biomes.
- [ ] Add simple cave generation. (Should be easy compared to full dungeons.)
- [ ] Implement quests.
- [ ] Very simple quest generation.

~~Create a simple scenario / planet with a dungeon (Diablo 1 complexity should be enough for now (I mean a small town and a multilevel dungeon), especially since the class design/combat design needs to be kind of like... found).~~ (I think I might be able to do the continent generator directly.)

---
Mobs
- [ ] Add wild animals (at least a few)
- [ ] Add mobs - camps, forts bandits etc -
- [ ] Fix mob turning

---
Items
- [ ] Basic crafting materials
- [ ] Basic weapons / clothes
- [ ] Starter items
- [ ] Maybe a few simple crafting recipes
---
Gameplay
- [ ] Need more experiments, both combat and the overall map design

---
Sounds
- [ ] Implement/add ui sounds
- [ ] Implement/add footstep sounds
- [ ] Implement/add spell sounds
- [ ] Implement/add melee sounds
- [ ] Ambient sounds

---
Development quality of life (These would make creating models with the current style a breeze)
- [ ] Finish the mesh data resource editor addon. Not having to export bodyparts constantly would make life a lot easier. Editing models inside the world with the generated terrarin (with the ingame colors/look) would be cool aswell.
- [x] ~Improve gdpose. Would make it simpler to mess with animations, as with the current workflow you can't see the final model in blender, only a skeleton.~ Turns out the [skeleton editor backport](https://github.com/godotengine/godot/pull/45699) already works quite well,  added it as a patch.

---
### Later

Dungeons (Can easily be a goal for 0.5. Especially if the continent generation works out. They will still require lots of work, even though Voxelman already supports them. Unfortunately right now the core is better equipped to work with an overworld.)

- [ ] A few basic dungeon props (Can't tell exactly yet, depends on the dungeon generator)
- [ ] Create an okay dungeon generator.
- [ ] (Probably) A new voxel mesher that works like VoxelMesherBlocky, but also uses isolevel.
- [ ] Try vertex displacement based on a global noise (per mesher). This might make everything look more organic.
- [ ] Empty voxel. A voxel type that makes Voxelman skip generating it's mesh.
- [ ] Mobs for the dungeons.

---
Networking
- [ ] Fix Networking
- [ ] Maybe a client should receive terrarin data from the server. This would make the terrarin editable serverside. It would also reduce client only computation.

Is shouldn't be that hard to fix, but it will need some work. Can probably wait until the game is actually somewhat playable.

---
Development quality of life (These would make creating models with the current style a breeze)
- [ ] Implement vertex edit mode for skeletons -> Depends on the mdr editor addon. (Not as important, not having to export after every change is the real time save)
- [ ] Finish, and port math_maker_gd to c++. (Not as important)

**Comment by Relintai** [comment]
I'm closing this, as I think I found a better way to go about it, but I want to keep this for future reference. Will open a new one soon.
